# action.yml
name: 'Jigger - Helm Tools - Push'
description: 'Pushes a local chart to a ChartMusem or OCI compatible registry. Supports token based auth and Chart.yaml version override.'
branding:
  color: 'green'
  icon: 'upload-cloud'
inputs:
  oci:
    description: 'API Token with read/write permissions to the helm registry'
    required: true
  access-token:
    description: 'API Token with read/write permissions to the helm registry'
    required: false
    default: ''
  username:
    description: 'Username read/write permissions to the helm registry'
    required: false
    default: ''
  password:
    description: 'Password with read/write permissions to the helm registry'
    required: false
    default: ''
  registry-url:
    description: 'Repository url'
    required: true
    default: ''
  chart-folder:
      description: 'Relative path to chart folder'
      required: false
      default: 'chart'
  version:
    description: 'Chart Version'
    required: false
    default: ''
  appVersion:
    description: 'App Version'
    required: false
    default: ''
  force:
    description: 'Whether or not to override existing chart with same version'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CHART_FOLDER: ${{ inputs.chart-folder }}
    SOME_INPUT: ${{ inputs.some }}
    FORCE: ${{ inputs.force }}
    REGISTRY_URL: ${{ inputs.registry-url }}
    REGISTRY_ACCESS_TOKEN: ${{ inputs.access-token }}
    REGISTRY_USERNAME: ${{ inputs.username }}
    REGISTRY_PASSWORD: ${{ inputs.password }}
    REGISTRY_VERSION: ${{ inputs.version }}
    REGISTRY_APPVERSION: ${{ inputs.appVersion }}
    OCI_ENABLED: ${{ inputs.oci }}
